'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("223.255.178.194")>  _
        Public Property cfg_src_hostname() As String
            Get
                Return CType(Me("cfg_src_hostname"),String)
            End Get
            Set
                Me("cfg_src_hostname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11433")>  _
        Public Property cfg_src_port() As String
            Get
                Return CType(Me("cfg_src_port"),String)
            End Get
            Set
                Me("cfg_src_port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ntlsdoc")>  _
        Public Property cfg_src_usrname() As String
            Get
                Return CType(Me("cfg_src_usrname"),String)
            End Get
            Set
                Me("cfg_src_usrname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ntls@2121")>  _
        Public Property cfg_src_pw() As String
            Get
                Return CType(Me("cfg_src_pw"),String)
            End Get
            Set
                Me("cfg_src_pw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ntls")>  _
        Public Property cfg_src_db() As String
            Get
                Return CType(Me("cfg_src_db"),String)
            End Get
            Set
                Me("cfg_src_db") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TIM")>  _
        Public Property cfg_tar_hostname() As String
            Get
                Return CType(Me("cfg_tar_hostname"),String)
            End Get
            Set
                Me("cfg_tar_hostname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cfg_tar_port() As String
            Get
                Return CType(Me("cfg_tar_port"),String)
            End Get
            Set
                Me("cfg_tar_port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("sa")>  _
        Public Property cfg_tar_usrname() As String
            Get
                Return CType(Me("cfg_tar_usrname"),String)
            End Get
            Set
                Me("cfg_tar_usrname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("!QAZxdr5")>  _
        Public Property cfg_tar_pw() As String
            Get
                Return CType(Me("cfg_tar_pw"),String)
            End Get
            Set
                Me("cfg_tar_pw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TLS")>  _
        Public Property cfg_tar_db() As String
            Get
                Return CType(Me("cfg_tar_db"),String)
            End Get
            Set
                Me("cfg_tar_db") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("vntechlink@gmail.com")>  _
        Public Property cfg_sender() As String
            Get
                Return CType(Me("cfg_sender"),String)
            End Get
            Set
                Me("cfg_sender") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("!QAZxdr5")>  _
        Public Property cfg_sender_pw() As String
            Get
                Return CType(Me("cfg_sender_pw"),String)
            End Get
            Set
                Me("cfg_sender_pw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cfg_recipients() As String
            Get
                Return CType(Me("cfg_recipients"),String)
            End Get
            Set
                Me("cfg_recipients") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2019-05-05")>  _
        Public Property cfg_spt() As Date
            Get
                Return CType(Me("cfg_spt"),Date)
            End Get
            Set
                Me("cfg_spt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")>  _
        Public Property smtp_server() As String
            Get
                Return CType(Me("smtp_server"),String)
            End Get
            Set
                Me("smtp_server") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("587")>  _
        Public Property smtp_port() As Integer
            Get
                Return CType(Me("smtp_port"),Integer)
            End Get
            Set
                Me("smtp_port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property cfg_int_day() As String
            Get
                Return CType(Me("cfg_int_day"),String)
            End Get
            Set
                Me("cfg_int_day") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property cfg_int_hrs() As String
            Get
                Return CType(Me("cfg_int_hrs"),String)
            End Get
            Set
                Me("cfg_int_hrs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property cfg_int_min() As String
            Get
                Return CType(Me("cfg_int_min"),String)
            End Get
            Set
                Me("cfg_int_min") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dummy() As String
            Get
                Return CType(Me("dummy"),String)
            End Get
            Set
                Me("dummy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property session_number() As Integer
            Get
                Return CType(Me("session_number"),Integer)
            End Get
            Set
                Me("session_number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT dbo.MAINSO.DATETIME AS DATETIME, CONVERT(nchar(8), getdate(), 112) AS XA00"& _ 
            "1, '' AS XA002, dbo.MAINSO.SORNO AS XA003, LTRIM(dbo.MAINSO.REV) AS XA004, dbo.M"& _ 
            "AINSO.CUS AS XA005, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"CONVERT(nchar(8), dbo.MAINSO.TDATE, 112) AS XA006, dbo.M"& _ 
            "AINSO.CUS AS XA007, LEFT(dbo.CURRENCY.SYM, 3) AS XA008, dbo.MAINSO.WEIGHTUNIT AS"& _ 
            " XA009, dbo.MAINSO.MEASUNIT AS XA010, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"'' AS XA011, CASE WHEN dbo.MAINSO.REV "& _ 
            "> 1 THEN 2 ELSE 1 END AS XA012, '' AS XA013, '' AS XA014, 'PR001' AS XA015"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"FROM"& _ 
            " dbo.MAINSO INNER JOIN dbo.CURRENCY ON dbo.MAINSO.CUR = dbo.CURRENCY.CUR"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"WHERE "& _ 
            "(((dbo.MAINSO.DATETIME) > '{0}') AND ((dbo.MAINSO.CUS) Like '%VN'))"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ORDER BY db"& _ 
            "o.MAINSO.DATETIME ASC")>  _
        Public Property strCmdMO() As String
            Get
                Return CType(Me("strCmdMO"),String)
            End Get
            Set
                Me("strCmdMO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT '' AS XB001, '' AS XB002, dbo.SOT.SORNO AS XB003, LTRIM(dbo.SOT.REV) AS XB"& _ 
            "004, RIGHT(10000 + dbo.SOT.ITEMNO, 4) AS XB005, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"dbo.SOT.CODE AS XB006, conve"& _ 
            "rt(numeric(16,3), dbo.SOT.QTY) AS XB007, convert(numeric(21,6), dbo.SOT.UP) AS X"& _ 
            "B008, CONVERT(nchar(8), dbo.SOT.RETD, 112) AS XB009, '' AS XB010, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"'' AS XB01"& _ 
            "1, '' AS XB012, CASE WHEN dbo.SOT.REV > 1 THEN 2 ELSE 1 END AS XB013, 0 AS XB014"& _ 
            ", '' AS XB015"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"FROM dbo.SOT"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"WHERE (((dbo.SOT.DATETIME) > '{0}') AND ((dbo.SOT.C"& _ 
            "US) Like '%VN'))"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ORDER BY dbo.SOT.DATETIME ASC")>  _
        Public Property strCmdSO() As String
            Get
                Return CType(Me("strCmdSO"),String)
            End Get
            Set
                Me("strCmdSO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source={0},{1}; Network Library=dbmssocn; Initial Catalog={2}; User ID={3}; "& _ 
            "Password={4}")>  _
        Public Property strCNHK() As String
            Get
                Return CType(Me("strCNHK"),String)
            End Get
            Set
                Me("strCNHK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source={0}; Initial Catalog={1}; User ID={2}; Password={3}")>  _
        Public Property strCNVN() As String
            Get
                Return CType(Me("strCNVN"),String)
            End Get
            Set
                Me("strCNVN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT RTRIM(dbo.COPMA.MA001) AS MA001, RTRIM(dbo.COPMA.MA002) AS MA002, RTRIM(db"& _ 
            "o.COPMA.MA003) AS MA003, RTRIM(dbo.COPMA.MA004) AS MA004"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"FROM dbo.COPMA")>  _
        Public Property strCmdCUS() As String
            Get
                Return CType(Me("strCmdCUS"),String)
            End Get
            Set
                Me("strCmdCUS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT CONVERT(nvarchar(40), RTRIM(dbo.COPMG.MG002)) AS MG002, RTRIM(dbo.COPMG.MG"& _ 
            "003) AS MG003"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"FROM dbo.COPMG")>  _
        Public Property strCmdPRO() As String
            Get
                Return CType(Me("strCmdPRO"),String)
            End Get
            Set
                Me("strCmdPRO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("!QAZxdr5")>  _
        Public Property supw() As String
            Get
                Return CType(Me("supw"),String)
            End Get
            Set
                Me("supw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dear Mr/Madam,"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SOT session number {0} has been completed."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Total Failed to Del"& _ 
            "ete or Update Main Order: {1}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Total Failed to Delete or Update Sub Order: {2}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
            "Total Failed Import due to missing product code: {3}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Total Successfully Delete "& _ 
            "Sub Order: {4}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Total Successfully Update Sub Order: {5}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Total Successfully Imp"& _ 
            "ort New Sub Order: {6}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Please find in attach the details of this session."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Th"& _ 
            "ank you and Best regards,"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ERP Team")>  _
        Public Property notification_email_body() As String
            Get
                Return CType(Me("notification_email_body"),String)
            End Get
            Set
                Me("notification_email_body") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT CONVERT(nchar(8), getdate(), 112) AS XA001, '' AS XA002, dbo.MAINSOTEMPDEL"& _ 
            ".SORNO AS XA003, LTRIM(dbo.MAINSOTEMPDEL.REV) AS XA004, dbo.MAINSOTEMPDEL.CUS AS"& _ 
            " XA005, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"CONVERT(nchar(8), dbo.MAINSOTEMPDEL.TDATE, 112) AS XA006, dbo.MAINSO"& _ 
            "TEMPDEL.CUS AS XA007, ntls.dbo.CURRENCY.SYM AS XA008, dbo.MAINSOTEMPDEL.WEIGHTUN"& _ 
            "IT AS XA009, dbo.MAINSOTEMPDEL.MEASUNIT AS XA010, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"'' AS XA011, 3 AS XA012, '"& _ 
            "' AS XA013, '' AS XA014, 'PR001' AS XA015"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"FROM dbo.MAINSOTEMPDEL INNER JOIN ntl"& _ 
            "s.dbo.CURRENCY ON dbo.MAINSOTEMPDEL.CUR = ntls.dbo.CURRENCY.CUR"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"WHERE (((dbo.MA"& _ 
            "INSOTEMPDEL.DATETIME) > '{0}') AND ((dbo.MAINSOTEMPDEL.CUS) Like '%VN'))"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ORDER "& _ 
            "BY dbo.MAINSOTEMPDEL.DATETIME ASC")>  _
        Public Property strCmdDelMO() As String
            Get
                Return CType(Me("strCmdDelMO"),String)
            End Get
            Set
                Me("strCmdDelMO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT '' AS XB001, '' AS XB002, dbo.SOTTEMPDEL.SORNO AS XB003, LTRIM(dbo.SOTTEMP"& _ 
            "DEL.REV) AS XB004, RIGHT(10000 + dbo.SOTTEMPDEL.ITEMNO, 4) AS XB005, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"dbo.SOT"& _ 
            "TEMPDEL.CODE AS XB006, convert(numeric(16,3), dbo.SOTTEMPDEL.QTY) AS XB007, conv"& _ 
            "ert(numeric(21,6), dbo.SOTTEMPDEL.UP) AS XB008, CONVERT(nchar(8), dbo.SOTTEMPDEL"& _ 
            ".RETD, 112) AS XB009, '' AS XB010, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(9)&Global.Microsoft.VisualBasic.ChrW(9)&"'' AS XB011, '' AS XB012, 3 AS XB013, 0 A"& _ 
            "S XB014, '' AS XB015"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"FROM dbo.SOTTEMPDEL"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"WHERE (((dbo.SOTTEMPDEL.DATETIME) > '"& _ 
            "{0}') AND ((dbo.SOTTEMPDEL.CUS) Like '%VN'))"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ORDER BY dbo.SOTTEMPDEL.DATETIME A"& _ 
            "SC")>  _
        Public Property strCmdDelSO() As String
            Get
                Return CType(Me("strCmdDelSO"),String)
            End Get
            Set
                Me("strCmdDelSO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ntls@2252")>  _
        Public Property sa_pw() As String
            Get
                Return CType(Me("sa_pw"),String)
            End Get
            Set
                Me("sa_pw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT RTRIM(dbo.MAINSODIC.XA001) AS XA001, RTRIM(dbo.MAINSODIC.XA002) AS XA002, "& _ 
            "RTRIM(dbo.MAINSODIC.XA003) AS XA003"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"FROM dbo.MAINSODIC")>  _
        Public Property strCmdDIC() As String
            Get
                Return CType(Me("strCmdDIC"),String)
            End Get
            Set
                Me("strCmdDIC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT * FROM dbo.BLCOPXB")>  _
        Public Property strCmdBL() As String
            Get
                Return CType(Me("strCmdBL"),String)
            End Get
            Set
                Me("strCmdBL") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Sales_Order_Transformation.My.MySettings
            Get
                Return Global.Sales_Order_Transformation.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
