'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("223.255.178.194")>  _
        Public Property cfg_src_hostname() As String
            Get
                Return CType(Me("cfg_src_hostname"),String)
            End Get
            Set
                Me("cfg_src_hostname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11433")>  _
        Public Property cfg_src_port() As String
            Get
                Return CType(Me("cfg_src_port"),String)
            End Get
            Set
                Me("cfg_src_port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ntlsdoc")>  _
        Public Property cfg_src_usrname() As String
            Get
                Return CType(Me("cfg_src_usrname"),String)
            End Get
            Set
                Me("cfg_src_usrname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ntls@2121")>  _
        Public Property cfg_src_pw() As String
            Get
                Return CType(Me("cfg_src_pw"),String)
            End Get
            Set
                Me("cfg_src_pw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ntls")>  _
        Public Property cfg_src_db() As String
            Get
                Return CType(Me("cfg_src_db"),String)
            End Get
            Set
                Me("cfg_src_db") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TIM")>  _
        Public Property cfg_tar_hostname() As String
            Get
                Return CType(Me("cfg_tar_hostname"),String)
            End Get
            Set
                Me("cfg_tar_hostname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cfg_tar_port() As String
            Get
                Return CType(Me("cfg_tar_port"),String)
            End Get
            Set
                Me("cfg_tar_port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("sa")>  _
        Public Property cfg_tar_usrname() As String
            Get
                Return CType(Me("cfg_tar_usrname"),String)
            End Get
            Set
                Me("cfg_tar_usrname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("!QAZxdr5")>  _
        Public Property cfg_tar_pw() As String
            Get
                Return CType(Me("cfg_tar_pw"),String)
            End Get
            Set
                Me("cfg_tar_pw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TLS")>  _
        Public Property cfg_tar_db() As String
            Get
                Return CType(Me("cfg_tar_db"),String)
            End Get
            Set
                Me("cfg_tar_db") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("vntechlink@gmail.com")>  _
        Public Property cfg_sender() As String
            Get
                Return CType(Me("cfg_sender"),String)
            End Get
            Set
                Me("cfg_sender") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("!QAZxdr5")>  _
        Public Property cfg_sender_pw() As String
            Get
                Return CType(Me("cfg_sender_pw"),String)
            End Get
            Set
                Me("cfg_sender_pw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cfg_recipients() As String
            Get
                Return CType(Me("cfg_recipients"),String)
            End Get
            Set
                Me("cfg_recipients") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cfg_spt() As String
            Get
                Return CType(Me("cfg_spt"),String)
            End Get
            Set
                Me("cfg_spt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")>  _
        Public Property smtp_server() As String
            Get
                Return CType(Me("smtp_server"),String)
            End Get
            Set
                Me("smtp_server") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("587")>  _
        Public Property smtp_port() As Integer
            Get
                Return CType(Me("smtp_port"),Integer)
            End Get
            Set
                Me("smtp_port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property cfg_int_day() As String
            Get
                Return CType(Me("cfg_int_day"),String)
            End Get
            Set
                Me("cfg_int_day") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property cfg_int_hrs() As String
            Get
                Return CType(Me("cfg_int_hrs"),String)
            End Get
            Set
                Me("cfg_int_hrs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property cfg_int_min() As String
            Get
                Return CType(Me("cfg_int_min"),String)
            End Get
            Set
                Me("cfg_int_min") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dummy() As String
            Get
                Return CType(Me("dummy"),String)
            End Get
            Set
                Me("dummy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property session_number() As Integer
            Get
                Return CType(Me("session_number"),Integer)
            End Get
            Set
                Me("session_number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source={0}; Initial Catalog={1}; User ID={2}; Password={3}")>  _
        Public Property strCNVN() As String
            Get
                Return CType(Me("strCNVN"),String)
            End Get
            Set
                Me("strCNVN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("!QAZxdr5")>  _
        Public Property supw() As String
            Get
                Return CType(Me("supw"),String)
            End Get
            Set
                Me("supw") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dear Sir/Madam,"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"* Please don't reply this email!"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"This is an automatic email"& _ 
            " generated by ERP Interface to keep you posted on daily sales orders tranformati"& _ 
            "on from Multiable HK to Workflow VN. "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SOT session number {0} has been complet"& _ 
            "ed."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Start point: {6}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Total failed to update main order: {1}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Total failed to u"& _ 
            "pdate sub order: {2}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Total failed importing due to missing product code: {3}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"T"& _ 
            "otal successfully update sub order: {4}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Total successfully place new sub order:"& _ 
            " {5}"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Please find in attach the details of this session."&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Thank you and Best r"& _ 
            "egards,"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"ERP Team")>  _
        Public Property notification_email_body() As String
            Get
                Return CType(Me("notification_email_body"),String)
            End Get
            Set
                Me("notification_email_body") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT RTRIM(dbo.MAINSODIC.XA001) AS XA001, RTRIM(dbo.MAINSODIC.XA002) AS XA002, "& _ 
            "RTRIM(dbo.MAINSODIC.XA003) AS XA003"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"FROM dbo.MAINSODIC")>  _
        Public Property strCmdDIC() As String
            Get
                Return CType(Me("strCmdDIC"),String)
            End Get
            Set
                Me("strCmdDIC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT * FROM dbo.BLCOPXB")>  _
        Public Property strCmdBL() As String
            Get
                Return CType(Me("strCmdBL"),String)
            End Get
            Set
                Me("strCmdBL") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=223.255.178.194,11433;Initial Catalog=ntls;Persist Security Info=True"& _ 
            ";User ID=ntlsdoc;Password=ntls@2121")>  _
        Public ReadOnly Property ntlsConnectionString() As String
            Get
                Return CType(Me("ntlsConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=14.161.39.188;Initial Catalog=TECHLINK;Persist Security Info=True;Use"& _ 
            "r ID=sa;Password=dsc@123")>  _
        Public ReadOnly Property TECHLINKConnectionString() As String
            Get
                Return CType(Me("TECHLINKConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=223.255.178.194,11433;Initial Catalog=ntls_sot;Persist Security Info="& _ 
            "True;User ID=sa;Password=ntls@2252;Pooling=False")>  _
        Public ReadOnly Property ntls_sotConnectionString() As String
            Get
                Return CType(Me("ntls_sotConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=14.161.39.188;Initial Catalog=DSCSYS;Persist Security Info=True;User "& _ 
            "ID=sa;Password=dsc@123")>  _
        Public ReadOnly Property DSCSYSConnectionString() As String
            Get
                Return CType(Me("DSCSYSConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=14.161.39.188;Initial Catalog=SOT;Persist Security Info=True;User ID="& _ 
            "sa;Password=dsc@123")>  _
        Public ReadOnly Property SOTConnectionString() As String
            Get
                Return CType(Me("SOTConnectionString"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Sales_Order_Transformation.My.MySettings
            Get
                Return Global.Sales_Order_Transformation.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
